substitutions:
  devicename: mastercloset
  upper_devicename: Mastercloset

esphome:
  name: $devicename
  on_boot:
    then:
      - script.execute: consider_deep_sleep
      
esp32:
  board: esp32-s2-saola-1
  framework:
    type: esp-idf


# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "1ac67eafeb9be61e62ad98a4a9d95d56"
#  password: !secret wifi_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


  manual_ip:
    static_ip: 192.168.50.165
    gateway: 192.168.50.1
    subnet: 255.255.255.0
    dns1: 192.168.50.1

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: $devicename "-ap"
    password: !secret wifi_password
    
    
binary_sensor:
  - platform: homeassistant
    id: prevent_deep_sleep
    name: Prevent Deep Sleep
    entity_id: input_boolean.prevent_deep_sleep
    
  - platform: gpio
    pin:
      number: 5
      mode: INPUT
    name: "PIR Motion"
    device_class: motion
    filters:
      - delayed_off: 500ms
      
      
deep_sleep:
  id: deep_sleep_control
  run_duration: 15s
  sleep_duration: 200s
  wakeup_pin: 4
  wakeup_pin_mode: INVERT_WAKEUP

script:
  - id: consider_deep_sleep
    mode: queued
    then:
      - delay: 10s
      - if:
          condition:
            binary_sensor.is_on: prevent_deep_sleep
          then:
            - logger.log: 'Helper is on. Skipping sleep, per prevent_deep_sleep'
          else:
            - logger.log: 'Entering deep sleep mode'
            - deep_sleep.enter: deep_sleep_control
      - script.execute: consider_deep_sleep
